---
- name: Ensuring consul folder is exist
  file:
    path: "{{ database_consul_workdir }}"
    owner: "{{ ansible_user }}"
    state: directory
    mode: 0775

- name: Ensuring directory {{ database_consul_datadir }} folder exists
  file:
    path: "{{ database_consul_datadir }}"
    owner: "{{ ansible_user }}"
    state: directory
    mode: '0775'

- name: Copy consul config to consul workdir
  template:
    src: consul/consul-config.json.j2
    dest: "{{ database_consul_workdir }}/consul-config.json"
    owner: "{{ ansible_user }}"
    # mode: 0644

- name: Copy docker compose to consul workdir
  template:
    src: consul/docker-compose.yml.j2
    dest: "{{ database_consul_workdir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    # mode: 0644

- name: Running consul 
  community.docker.docker_compose_v2:
    project_src: "{{ database_consul_workdir }}"
    state: present
