---
- name: Ensuring directory {{ database_haproxy_workdir }} exists
  file:
    path: "{{ database_haproxy_workdir }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    state: directory

- name: Ensuring config directories exist
  file:
    path: "{{ database_haproxy_workdir }}/{{ item }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    state: directory
  loop:
    - confd/conf.d
    - confd/templates

- name: Copy haproxy config to workdir
  template:
    src: "{{ item.src }}"
    dest: "{{ database_haproxy_workdir }}/{{ item.dest }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
  loop:
    - { src: 'haproxy/haproxy_confd_template.toml.j2', dest: 'confd/conf.d/confd_template.toml' }
    - { src: 'confd/confd.toml.j2', dest: 'confd/confd.toml' }
    - { src: 'haproxy/haproxy.cfg.tmpl.j2', dest: 'confd/templates/haproxy.cfg.tmpl' }

- name: Copy docker compose file
  template:
    src: haproxy/docker-compose.yml.j2
    dest: "{{ database_haproxy_workdir }}/docker-compose.yml"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: Running haproxy
  community.docker.docker_compose_v2:
    project_src: "{{ database_haproxy_workdir }}"
    state: present

- name: Ensure haproxy is started
  wait_for:
    host: "{{ ansible_host }}"
    port: "{{ database_haproxy_listen_port.stats }}"
    state: started
    timeout: 60
    delay: 5
    