- name: Deploy etcd
  import_tasks: etcd.yaml
  become: yes
  tags:
    - database_etcd
    - database

# - name: Deploy consul
#   import_tasks: consul.yaml
#   become: yes
#   tags:
#     - database_consul
#     - database

- name: Deploy postgres
  import_tasks: postgres.yaml
  become: yes
  tags:
    - database_postgres
    - database

- name: Deploy pgbouncer
  import_tasks: pgbouncer.yml
  become: yes
  tags:
    - database_pgbouncer
    - database

- name: Deploy haproxy
  import_tasks: haproxy.yml
  become: yes
  tags:
    - database_haproxy
    - database

- name: Deploy keepalived
  import_tasks: keepalived.yml
  become: yes
  tags:
    - database_keepalived
    - database
