---
- name: Ensuring app folder is exist
  file:
    path: "{{ server_workdir }}"
    state: directory
    mode: '0755'

- name: Copy docker compose to app workdir
  template:
    src: docker-compose.yml.j2
    dest: "{{ server_workdir }}/docker-compose.yml"

- name: Copy env to app workdir
  template:
    src: backend.env.j2
    dest: "{{ server_workdir }}/backend.env"

- name: Running server
  community.docker.docker_compose_v2:
    project_src: "{{ server_workdir }}"
    state: present