---
- name: Ensuring advisor folder is exist
  file:
    path: "{{ advisor_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'

- name: Copy docker compose to advisor workdir
  template:
    src: docker-compose-advisor.yml.j2
    dest: "{{ advisor_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"

- name: Running cadvisor, node-exporter
  community.docker.docker_compose_v2:
    project_src: "{{ advisor_dir }}"
    state: present
